[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200

# Remappings
remappings = [
    "@uniswap/v2-core/contracts/=src/v2-core/",
    "@uniswap/lib/contracts/=src/solidity-lib/",
    "@openzeppelin/contracts/=../foundry_projects/lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
